{
  description = "System Consultant Group's NixOS configuration";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    kime.url = "github:apersomany/kime";
    nixos-router = {
      url = "github:chayleaf/nixos-router";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    notnft = {
      url = "github:chayleaf/notnft";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    { self, nixpkgs, nixos-router, notnft, ... }@inputs:
    let
      username = "scg";
      userFullName = "System Consultant Group";
      gitUserName = "scg";
      gitUserEmail = "scg@scg.skku.ac.kr";
      pkgs = nixpkgs.legacyPackages.x86_64-linux;
      mkHost =
        name: extraModules:
        nixpkgs.lib.nixosSystem {
          specialArgs = {
            inherit
              self
              inputs
              username
              userFullName
              gitUserName
              gitUserEmail
              ;
          };
          modules = [
            { nixpkgs.hostPlatform = "x86_64-linux"; }
            (./. + "/hosts/${name}/configuration.nix")
          ]
          ++ extraModules;
        };
    in
    {
      nixosConfigurations = {
        router = mkHost "router" [
          nixos-router.nixosModules.default
          notnft.nixosModules.default
        ];
      };

      nixosModules = {
        base = ./modules/base;
        client = ./modules/client;
        server = ./modules/server;
      };

      formatter.x86_64-linux = pkgs.nixfmt;

      devShells.x86_64-linux.default = pkgs.mkShell {
        packages = with pkgs; [
          nixfmt
          nil
          nixd
          statix
          deadnix
          direnv
        ];
        shellHook = ''
          # Generate opencode.json with the username from flake.nix
          # (gitignored — regenerated by direnv on every directory entry)
          cat > opencode.json << 'JSONEOF'
          {
            "$schema": "https://opencode.ai/config.json",
            "default_agent": "NixOS",
            "permission": {
              "external_directory": {
                "/nix/store": "allow",
                "/run/current-system": "allow",
                "/etc/nixos": "allow",
                "/home/${username}/.local/share/opencode": "allow",
                "/tmp": "allow",
                "/tmp/opencode": "allow"
              }
            }
          }
          JSONEOF
        '';
      };
    };
}
