{
  description = "Donghyun Shin's NixOS configuration";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    kime.url = "github:apersomany/kime";
  };

  outputs =
    { self, nixpkgs, ... }@inputs:
    let
      username = "aperso";
      userFullName = "Donghyun Shin";
      gitUserName = "apersomany";
      gitUserEmail = "aperso@aperso.dev";
      pkgs = nixpkgs.legacyPackages.x86_64-linux;
      mkHost =
        name:
        nixpkgs.lib.nixosSystem {
          specialArgs = {
            inherit
              self
              inputs
              username
              userFullName
              gitUserName
              gitUserEmail
              ;
          };
          modules = [
            { nixpkgs.hostPlatform = "x86_64-linux"; }
            (./. + "/hosts/${name}/configuration.nix")
          ];
        };
    in
    {
      nixosConfigurations = {
        workstation = mkHost "workstation";
        laptop = mkHost "laptop";
      };

      nixosModules = {
        base = ./modules/base;
        client = ./modules/client;
        server = ./modules/server;
      };

      formatter.x86_64-linux = pkgs.treefmt;

      devShells.x86_64-linux.default = pkgs.mkShell {
        packages = with pkgs; [
          treefmt
          nil
          nixd
          statix
          deadnix
          direnv
        ];
        shellHook = ''
          # Generate opencode.json with the username from flake.nix
          # (gitignored — regenerated by direnv on every directory entry)
          cat > opencode.json << 'JSONEOF'
          {
            "$schema": "https://opencode.ai/config.json",
            "default_agent": "NixOS",
            "permission": {
              "external_directory": {
                "/nix/store": "allow",
                "/run/current-system": "allow",
                "/etc/nixos": "allow",
                "/home/${username}/.local/share/opencode": "allow",
                "/tmp": "allow",
                "/tmp/opencode": "allow"
              }
            }
          }
          JSONEOF
        '';
      };
    };
}
